language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
before_script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
script: vendor/bin/phpunit --configuration test/phpunit.xml.dist
